# General Jekyll Config
pygments: true
url: tmcharly.github.io
lsi: false
exclude: [ README.md]
markdown: kramdown
permalink: /blog/:year/:title/
lastvideo: https://www.youtube.com/watch?v=sHeRLnqJHSQ
